#!/bin/bash
#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -A hpc_startup_solmazir
#PBS -l walltime=01:00:00
#PBS -N featureCounts
#PBS -j oe

sampleDir=/project/solmazir/haoran/STAR_result/trimmed_mapping/results
outputDir=/project/solmazir/haoran/STAR_result/trimmed_mapping

featureCounts -T 20 -a /project/solmazir/haoran/refgenome/drought_filtered.gtf \
-o $outputDir/read.count -p -B -C -t exon -g gene_id  $sampleDir/sample_{13..36}/*.bam